export { H1 } from "./H1";
export { H2 } from "./H2";
export { H3 } from "./H3";
export { H4 } from "./H4";
export { P } from "./P";
export { Span } from "./Span";
export { Label } from "./Label";
export { Small } from "./Small";
export { Code } from "./Code";
